/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  guides: [
    {
      type: 'autogenerated',
      dirName: 'guides', // generate sidebar from the docs folder (or versioned_docs/<version>)
    },
  ],
  opencart: [
    {
      type: 'autogenerated',
      dirName: 'manual-opencart', // generate sidebar from the docs folder (or versioned_docs/<version>)
    },
  ],
  // oscommerce: [
  //   {
  //     type: 'autogenerated',
  //     dirName: 'manual-oscommerce', // generate sidebar from the docs folder (or versioned_docs/<version>)
  //   },
  // ],
  prestashop: [
    {
      type: 'autogenerated',
      dirName: 'manual-prestashop', // generate sidebar from the docs folder (or versioned_docs/<version>)
    },
  ],
  virtuemart: [
    {
      type: 'autogenerated',
      dirName: 'manual-virtuemart', // generate sidebar from the docs folder (or versioned_docs/<version>)
    },
  ],
  woocommerce: [
    {
      type: 'autogenerated',
      dirName: 'manual-woocommerce', // generate sidebar from the docs folder (or versioned_docs/<version>)
    },
  ],
  zencart: [
    {
      type: 'autogenerated',
      dirName: 'manual-zencart', // generate sidebar from the docs folder (or versioned_docs/<version>)
    },
  ],
};

module.exports = sidebars;
